name: cantwait28
description: A Flutter project that counts days down to exciting dates in the future.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  cloud_firestore: 5.4.1

  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  firebase_ui_auth: ^1.15.0
  intl: ^0.19.0
  firebase_auth: ^5.1.4
  bloc: ^8.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
